[pytest]
markers =
    test: Тесты Касса Розница

# Настройки логирования в файл
log_file = app.log
log_file_level = INFO
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

addopts = -o encoding=utf-8 -p no:teamcity -v
